---
- name: apt source update
  lineinfile:
    path: /etc/apt/sources.list
    line: 'deb http://mirrordirector.raspbian.org/raspbian/ stretch main contrib non-free rpi'
    insertafter: deb http://mirrordirector.raspbian.org/raspbian/ jessie
    backup: yes

#    - name: create preferences file if it doesn't exist
#      file: path=/etc/apt/preferences state=touch

#    - name: prioritize jessie over stretch
#      blockinfile:
#        path: /etc/apt/preferences
#        block: |
#          Package: *
#          Pin: release n=jessie
#          Pin-Priority: 600
#        backup: yes

- name: install php7
  apt: name={{item}} default_release=stretch state=present update_cache=yes
  with_items:
    - php7.0
    - php7.0-curl
    - php7.0-gd
    - php7.0-fpm
    - php7.0-cli
    - php7.0-opcache
    - php7.0-mbstring
    - php7.0-xml
    - php7.0-zip
    - php7.0-mysql
