---
  - hosts: loadbalancer
    become: true
    gather_facts: false
    tasks:
      - name: verify nginx service
        command: service nginx status
#        changed_when: false

      - name: verify nginx is listening on port 80
        wait_for: port=80 timeout=1

  - hosts: webserver
    become: true
    gather_facts: false
    tasks:
      - name: verify apache2 service
        command: service apache2 status

      - name: verify apache2 is listening on port 81
        wait_for: port=81 timeout=1

  - hosts: database
    become: true
    tasks:
      - name: verify mysql service
        command: service mysql status

      - name: verify mysql is listening on port 3306
        wait_for: host={{ ansible_wlan0.ipv4.address }}  port=3306 timeout=1

  - hosts: loadbalancer
    gather_facts: false
    tasks:
      - name: verify end to end response lb to web
        uri:  url=http://{{item}}:81 return_content=yes
#        with_items: raspberrypi2
        with_items:  "{{ groups.webserver }}"
        register: app_index

      - fail: msg="index failed to return content"
        when: "'Apache' not in item.content"
        with_items: "{{app_index.results}}"

#    tasks:
#      - name: verify end to end response lb to db
#        uri:  url=http://{{item}}/db return_content=yes
#        with_items:  "{{ groups.database }}"
#        register: db_index

#      - fail: msg="index failed to return content"
#        when: "'Database Connected from' not in item.content"
#        with_items: "{{db_index.results}}"

  - hosts: control
    gather_facts: false
    tasks:
      - name: verify end to end response control to lb
        uri: url=http://{{item}} return_content=yes
        with_items: "{{ groups.loadbalancer }}"
#        with_items: raspberrypi2
        register: lb_index

      - fail: msg="index failed to return content"
        when: "'Apache' not in item.content"
        with_items: "{{ lb_index.results }}"
